services:
  orders_server:
    build: .
    ports:
      - "8000:8000"

  orders_db:
    image: 'bitnami/mongodb:4.4'
    restart: always
    ports: 
      - "8001:27017"
    volumes:
      - order_db:/bitnami/mongodb
    environment:
      - MONGODB_ROOT_USER=${MONGODB_USER}
      - MONGODB_ROOT_PASSWORD=${MONGODB_PASS}
      - MONGODB_DATABASE=${MONGODB_DB}
  
volumes:
  order_db: