// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/proto/reviews.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Review struct {
	OrderId              int64    `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rate                 int64    `protobuf:"varint,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Review) Reset()         { *m = Review{} }
func (m *Review) String() string { return proto.CompactTextString(m) }
func (*Review) ProtoMessage()    {}
func (*Review) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a0e5d53f29aa9, []int{0}
}

func (m *Review) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Review.Unmarshal(m, b)
}
func (m *Review) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Review.Marshal(b, m, deterministic)
}
func (m *Review) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Review.Merge(m, src)
}
func (m *Review) XXX_Size() int {
	return xxx_messageInfo_Review.Size(m)
}
func (m *Review) XXX_DiscardUnknown() {
	xxx_messageInfo_Review.DiscardUnknown(m)
}

var xxx_messageInfo_Review proto.InternalMessageInfo

func (m *Review) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *Review) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Review) GetRate() int64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *Review) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Review) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type GetReviewsFromRestaurantRequest struct {
	RestaurantId         int64    `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReviewsFromRestaurantRequest) Reset()         { *m = GetReviewsFromRestaurantRequest{} }
func (m *GetReviewsFromRestaurantRequest) String() string { return proto.CompactTextString(m) }
func (*GetReviewsFromRestaurantRequest) ProtoMessage()    {}
func (*GetReviewsFromRestaurantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a0e5d53f29aa9, []int{1}
}

func (m *GetReviewsFromRestaurantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReviewsFromRestaurantRequest.Unmarshal(m, b)
}
func (m *GetReviewsFromRestaurantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReviewsFromRestaurantRequest.Marshal(b, m, deterministic)
}
func (m *GetReviewsFromRestaurantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReviewsFromRestaurantRequest.Merge(m, src)
}
func (m *GetReviewsFromRestaurantRequest) XXX_Size() int {
	return xxx_messageInfo_GetReviewsFromRestaurantRequest.Size(m)
}
func (m *GetReviewsFromRestaurantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReviewsFromRestaurantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReviewsFromRestaurantRequest proto.InternalMessageInfo

func (m *GetReviewsFromRestaurantRequest) GetRestaurantId() int64 {
	if m != nil {
		return m.RestaurantId
	}
	return 0
}

type GetReviewsFromRestaurantResponse struct {
	Reviews              []*Review `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetReviewsFromRestaurantResponse) Reset()         { *m = GetReviewsFromRestaurantResponse{} }
func (m *GetReviewsFromRestaurantResponse) String() string { return proto.CompactTextString(m) }
func (*GetReviewsFromRestaurantResponse) ProtoMessage()    {}
func (*GetReviewsFromRestaurantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a0e5d53f29aa9, []int{2}
}

func (m *GetReviewsFromRestaurantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReviewsFromRestaurantResponse.Unmarshal(m, b)
}
func (m *GetReviewsFromRestaurantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReviewsFromRestaurantResponse.Marshal(b, m, deterministic)
}
func (m *GetReviewsFromRestaurantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReviewsFromRestaurantResponse.Merge(m, src)
}
func (m *GetReviewsFromRestaurantResponse) XXX_Size() int {
	return xxx_messageInfo_GetReviewsFromRestaurantResponse.Size(m)
}
func (m *GetReviewsFromRestaurantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReviewsFromRestaurantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReviewsFromRestaurantResponse proto.InternalMessageInfo

func (m *GetReviewsFromRestaurantResponse) GetReviews() []*Review {
	if m != nil {
		return m.Reviews
	}
	return nil
}

type GetReviewsFromUserResponse struct {
	Reviews              []*Review `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetReviewsFromUserResponse) Reset()         { *m = GetReviewsFromUserResponse{} }
func (m *GetReviewsFromUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetReviewsFromUserResponse) ProtoMessage()    {}
func (*GetReviewsFromUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a0e5d53f29aa9, []int{3}
}

func (m *GetReviewsFromUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReviewsFromUserResponse.Unmarshal(m, b)
}
func (m *GetReviewsFromUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReviewsFromUserResponse.Marshal(b, m, deterministic)
}
func (m *GetReviewsFromUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReviewsFromUserResponse.Merge(m, src)
}
func (m *GetReviewsFromUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetReviewsFromUserResponse.Size(m)
}
func (m *GetReviewsFromUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReviewsFromUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReviewsFromUserResponse proto.InternalMessageInfo

func (m *GetReviewsFromUserResponse) GetReviews() []*Review {
	if m != nil {
		return m.Reviews
	}
	return nil
}

func init() {
	proto.RegisterType((*Review)(nil), "Review")
	proto.RegisterType((*GetReviewsFromRestaurantRequest)(nil), "GetReviewsFromRestaurantRequest")
	proto.RegisterType((*GetReviewsFromRestaurantResponse)(nil), "GetReviewsFromRestaurantResponse")
	proto.RegisterType((*GetReviewsFromUserResponse)(nil), "GetReviewsFromUserResponse")
}

func init() {
	proto.RegisterFile("src/proto/reviews.proto", fileDescriptor_c48a0e5d53f29aa9)
}

var fileDescriptor_c48a0e5d53f29aa9 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0xa9, 0x20, 0x95, 0x41, 0x3d, 0xcc, 0x41, 0x6a, 0x89, 0xb1, 0xd4, 0x0b, 0xa7, 0x25,
	0xc1, 0x07, 0x30, 0x9a, 0x80, 0x21, 0xde, 0x6a, 0xbc, 0x78, 0x21, 0xb5, 0x3b, 0x92, 0x26, 0xc2,
	0xd6, 0xd9, 0x2d, 0xc6, 0xc7, 0xf0, 0x8d, 0x7c, 0x34, 0xc3, 0x6e, 0x11, 0x8d, 0x21, 0xc4, 0x53,
	0x3b, 0xdf, 0x3f, 0x33, 0xf9, 0x67, 0xf3, 0x43, 0x47, 0x73, 0x36, 0x28, 0x58, 0x19, 0x35, 0x60,
	0x5a, 0xe6, 0xf4, 0xa6, 0x85, 0xad, 0xc2, 0xee, 0x4c, 0xa9, 0xd9, 0x0b, 0x39, 0xed, 0xa9, 0x7c,
	0x1e, 0xd0, 0xbc, 0x30, 0xef, 0x4e, 0x8c, 0x3f, 0x3c, 0x68, 0x26, 0xb6, 0x1d, 0x4f, 0xe1, 0x40,
	0xb1, 0x24, 0x9e, 0xe6, 0x32, 0xf0, 0x22, 0xaf, 0x5f, 0x4f, 0x7c, 0x5b, 0x4f, 0x24, 0x76, 0xc0,
	0x2f, 0xb5, 0x53, 0xf6, 0xac, 0xd2, 0x5c, 0x95, 0x13, 0x89, 0x08, 0x0d, 0x4e, 0x0d, 0x05, 0x75,
	0x4b, 0xed, 0x3f, 0x46, 0xd0, 0x96, 0xa4, 0x33, 0xce, 0x0b, 0x93, 0xab, 0x45, 0xd0, 0x88, 0xbc,
	0x7e, 0x2b, 0xf9, 0x89, 0xf0, 0x0c, 0x20, 0x63, 0x4a, 0x0d, 0xc9, 0x69, 0x6a, 0x82, 0x7d, 0xdb,
	0xd0, 0xaa, 0xc8, 0xb5, 0x89, 0xc7, 0x70, 0x7e, 0x4b, 0xc6, 0xb9, 0xd2, 0x63, 0x56, 0xf3, 0x84,
	0xb4, 0x49, 0x4b, 0x4e, 0x17, 0x26, 0xa1, 0xd7, 0x92, 0xb4, 0xc1, 0x0b, 0x38, 0xe2, 0x6f, 0xb8,
	0x31, 0x7c, 0xb8, 0x81, 0x13, 0x19, 0x8f, 0x20, 0xda, 0xbe, 0x47, 0x17, 0x6a, 0xa1, 0x09, 0x7b,
	0xe0, 0x57, 0xaf, 0x15, 0x78, 0x51, 0xbd, 0xdf, 0x1e, 0xfa, 0xc2, 0x0d, 0x24, 0x6b, 0x1e, 0x5f,
	0x41, 0xf8, 0x7b, 0xcd, 0x83, 0x26, 0xfe, 0xc7, 0x82, 0xe1, 0xa7, 0x07, 0xc7, 0xd5, 0xf8, 0x3d,
	0xf1, 0x32, 0xcf, 0x08, 0x53, 0x08, 0xb6, 0x59, 0xc3, 0x48, 0xec, 0xb8, 0x3e, 0xec, 0x89, 0x5d,
	0x77, 0xc5, 0x35, 0xbc, 0x03, 0xfc, 0x6b, 0x1b, 0x4f, 0x84, 0x4b, 0x83, 0x58, 0xa7, 0x41, 0x8c,
	0x56, 0x69, 0x08, 0xbb, 0x62, 0xfb, 0x8d, 0x71, 0xed, 0xa6, 0xf5, 0xe8, 0x8b, 0x2a, 0x40, 0x4d,
	0xfb, 0xb9, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x91, 0xb0, 0xd1, 0x0e, 0x70, 0x02, 0x00, 0x00,
}
