services:
  restaurants:
    build: .
    ports:
      - "9000:9000"

  restaurants_db:
    image: 'bitnami/mongodb:4.4'
    restart: always
    ports: 
      - "9001:27017"
    volumes:
      - restaurant_db:/bitnami/mongodb
    environment:
      - MONGODB_ROOT_USER=${MONGODB_USER}
      - MONGODB_ROOT_PASSWORD=${MONGODB_PASS}
      - MONGODB_DATABASE=${MONGODB_DB}
  
volumes:
  restaurant_db: