// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/proto/restaurants.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Restaurant struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image                string   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	IsOpen               bool     `protobuf:"varint,4,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Restaurant) Reset()         { *m = Restaurant{} }
func (m *Restaurant) String() string { return proto.CompactTextString(m) }
func (*Restaurant) ProtoMessage()    {}
func (*Restaurant) Descriptor() ([]byte, []int) {
	return fileDescriptor_d282ef766bb01f4c, []int{0}
}

func (m *Restaurant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Restaurant.Unmarshal(m, b)
}
func (m *Restaurant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Restaurant.Marshal(b, m, deterministic)
}
func (m *Restaurant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Restaurant.Merge(m, src)
}
func (m *Restaurant) XXX_Size() int {
	return xxx_messageInfo_Restaurant.Size(m)
}
func (m *Restaurant) XXX_DiscardUnknown() {
	xxx_messageInfo_Restaurant.DiscardUnknown(m)
}

var xxx_messageInfo_Restaurant proto.InternalMessageInfo

func (m *Restaurant) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Restaurant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Restaurant) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Restaurant) GetIsOpen() bool {
	if m != nil {
		return m.IsOpen
	}
	return false
}

type GetRestaurantsResponse struct {
	Data                 []*Restaurant `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetRestaurantsResponse) Reset()         { *m = GetRestaurantsResponse{} }
func (m *GetRestaurantsResponse) String() string { return proto.CompactTextString(m) }
func (*GetRestaurantsResponse) ProtoMessage()    {}
func (*GetRestaurantsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d282ef766bb01f4c, []int{1}
}

func (m *GetRestaurantsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRestaurantsResponse.Unmarshal(m, b)
}
func (m *GetRestaurantsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRestaurantsResponse.Marshal(b, m, deterministic)
}
func (m *GetRestaurantsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRestaurantsResponse.Merge(m, src)
}
func (m *GetRestaurantsResponse) XXX_Size() int {
	return xxx_messageInfo_GetRestaurantsResponse.Size(m)
}
func (m *GetRestaurantsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRestaurantsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRestaurantsResponse proto.InternalMessageInfo

func (m *GetRestaurantsResponse) GetData() []*Restaurant {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddRestaurantRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OpenHour             string   `protobuf:"bytes,2,opt,name=open_hour,json=openHour,proto3" json:"open_hour,omitempty"`
	CloseHour            string   `protobuf:"bytes,3,opt,name=close_hour,json=closeHour,proto3" json:"close_hour,omitempty"`
	Image                []byte   `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRestaurantRequest) Reset()         { *m = AddRestaurantRequest{} }
func (m *AddRestaurantRequest) String() string { return proto.CompactTextString(m) }
func (*AddRestaurantRequest) ProtoMessage()    {}
func (*AddRestaurantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d282ef766bb01f4c, []int{2}
}

func (m *AddRestaurantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRestaurantRequest.Unmarshal(m, b)
}
func (m *AddRestaurantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRestaurantRequest.Marshal(b, m, deterministic)
}
func (m *AddRestaurantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRestaurantRequest.Merge(m, src)
}
func (m *AddRestaurantRequest) XXX_Size() int {
	return xxx_messageInfo_AddRestaurantRequest.Size(m)
}
func (m *AddRestaurantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRestaurantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRestaurantRequest proto.InternalMessageInfo

func (m *AddRestaurantRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddRestaurantRequest) GetOpenHour() string {
	if m != nil {
		return m.OpenHour
	}
	return ""
}

func (m *AddRestaurantRequest) GetCloseHour() string {
	if m != nil {
		return m.CloseHour
	}
	return ""
}

func (m *AddRestaurantRequest) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type AddRestaurantResponse struct {
	RestaurantId         string   `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRestaurantResponse) Reset()         { *m = AddRestaurantResponse{} }
func (m *AddRestaurantResponse) String() string { return proto.CompactTextString(m) }
func (*AddRestaurantResponse) ProtoMessage()    {}
func (*AddRestaurantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d282ef766bb01f4c, []int{3}
}

func (m *AddRestaurantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRestaurantResponse.Unmarshal(m, b)
}
func (m *AddRestaurantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRestaurantResponse.Marshal(b, m, deterministic)
}
func (m *AddRestaurantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRestaurantResponse.Merge(m, src)
}
func (m *AddRestaurantResponse) XXX_Size() int {
	return xxx_messageInfo_AddRestaurantResponse.Size(m)
}
func (m *AddRestaurantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRestaurantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRestaurantResponse proto.InternalMessageInfo

func (m *AddRestaurantResponse) GetRestaurantId() string {
	if m != nil {
		return m.RestaurantId
	}
	return ""
}

type DeleteRestaurantRequest struct {
	RestaurantId         string   `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRestaurantRequest) Reset()         { *m = DeleteRestaurantRequest{} }
func (m *DeleteRestaurantRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRestaurantRequest) ProtoMessage()    {}
func (*DeleteRestaurantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d282ef766bb01f4c, []int{4}
}

func (m *DeleteRestaurantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRestaurantRequest.Unmarshal(m, b)
}
func (m *DeleteRestaurantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRestaurantRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRestaurantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRestaurantRequest.Merge(m, src)
}
func (m *DeleteRestaurantRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRestaurantRequest.Size(m)
}
func (m *DeleteRestaurantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRestaurantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRestaurantRequest proto.InternalMessageInfo

func (m *DeleteRestaurantRequest) GetRestaurantId() string {
	if m != nil {
		return m.RestaurantId
	}
	return ""
}

type DeleteRestaurantResponse struct {
	RestaurantId         string   `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRestaurantResponse) Reset()         { *m = DeleteRestaurantResponse{} }
func (m *DeleteRestaurantResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRestaurantResponse) ProtoMessage()    {}
func (*DeleteRestaurantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d282ef766bb01f4c, []int{5}
}

func (m *DeleteRestaurantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRestaurantResponse.Unmarshal(m, b)
}
func (m *DeleteRestaurantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRestaurantResponse.Marshal(b, m, deterministic)
}
func (m *DeleteRestaurantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRestaurantResponse.Merge(m, src)
}
func (m *DeleteRestaurantResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRestaurantResponse.Size(m)
}
func (m *DeleteRestaurantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRestaurantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRestaurantResponse proto.InternalMessageInfo

func (m *DeleteRestaurantResponse) GetRestaurantId() string {
	if m != nil {
		return m.RestaurantId
	}
	return ""
}

type UpdateRestaurantRequest struct {
	RestaurantId         string   `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OpenHour             string   `protobuf:"bytes,3,opt,name=open_hour,json=openHour,proto3" json:"open_hour,omitempty"`
	CloseHour            string   `protobuf:"bytes,4,opt,name=close_hour,json=closeHour,proto3" json:"close_hour,omitempty"`
	Image                []byte   `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRestaurantRequest) Reset()         { *m = UpdateRestaurantRequest{} }
func (m *UpdateRestaurantRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRestaurantRequest) ProtoMessage()    {}
func (*UpdateRestaurantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d282ef766bb01f4c, []int{6}
}

func (m *UpdateRestaurantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRestaurantRequest.Unmarshal(m, b)
}
func (m *UpdateRestaurantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRestaurantRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRestaurantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRestaurantRequest.Merge(m, src)
}
func (m *UpdateRestaurantRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRestaurantRequest.Size(m)
}
func (m *UpdateRestaurantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRestaurantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRestaurantRequest proto.InternalMessageInfo

func (m *UpdateRestaurantRequest) GetRestaurantId() string {
	if m != nil {
		return m.RestaurantId
	}
	return ""
}

func (m *UpdateRestaurantRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRestaurantRequest) GetOpenHour() string {
	if m != nil {
		return m.OpenHour
	}
	return ""
}

func (m *UpdateRestaurantRequest) GetCloseHour() string {
	if m != nil {
		return m.CloseHour
	}
	return ""
}

func (m *UpdateRestaurantRequest) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type UpdateRestaurantResponse struct {
	RestaurantId         string   `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRestaurantResponse) Reset()         { *m = UpdateRestaurantResponse{} }
func (m *UpdateRestaurantResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRestaurantResponse) ProtoMessage()    {}
func (*UpdateRestaurantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d282ef766bb01f4c, []int{7}
}

func (m *UpdateRestaurantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRestaurantResponse.Unmarshal(m, b)
}
func (m *UpdateRestaurantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRestaurantResponse.Marshal(b, m, deterministic)
}
func (m *UpdateRestaurantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRestaurantResponse.Merge(m, src)
}
func (m *UpdateRestaurantResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRestaurantResponse.Size(m)
}
func (m *UpdateRestaurantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRestaurantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRestaurantResponse proto.InternalMessageInfo

func (m *UpdateRestaurantResponse) GetRestaurantId() string {
	if m != nil {
		return m.RestaurantId
	}
	return ""
}

type GetOrdersRequest struct {
	RestaurantId         string   `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrdersRequest) Reset()         { *m = GetOrdersRequest{} }
func (m *GetOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrdersRequest) ProtoMessage()    {}
func (*GetOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d282ef766bb01f4c, []int{8}
}

func (m *GetOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersRequest.Unmarshal(m, b)
}
func (m *GetOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersRequest.Marshal(b, m, deterministic)
}
func (m *GetOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersRequest.Merge(m, src)
}
func (m *GetOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrdersRequest.Size(m)
}
func (m *GetOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersRequest proto.InternalMessageInfo

func (m *GetOrdersRequest) GetRestaurantId() string {
	if m != nil {
		return m.RestaurantId
	}
	return ""
}

type GetOrdersResponse struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Datetime             string   `protobuf:"bytes,2,opt,name=datetime,proto3" json:"datetime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrdersResponse) Reset()         { *m = GetOrdersResponse{} }
func (m *GetOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrdersResponse) ProtoMessage()    {}
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d282ef766bb01f4c, []int{9}
}

func (m *GetOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersResponse.Unmarshal(m, b)
}
func (m *GetOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersResponse.Marshal(b, m, deterministic)
}
func (m *GetOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersResponse.Merge(m, src)
}
func (m *GetOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrdersResponse.Size(m)
}
func (m *GetOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersResponse proto.InternalMessageInfo

func (m *GetOrdersResponse) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *GetOrdersResponse) GetDatetime() string {
	if m != nil {
		return m.Datetime
	}
	return ""
}

func init() {
	proto.RegisterType((*Restaurant)(nil), "Restaurant")
	proto.RegisterType((*GetRestaurantsResponse)(nil), "GetRestaurantsResponse")
	proto.RegisterType((*AddRestaurantRequest)(nil), "AddRestaurantRequest")
	proto.RegisterType((*AddRestaurantResponse)(nil), "AddRestaurantResponse")
	proto.RegisterType((*DeleteRestaurantRequest)(nil), "DeleteRestaurantRequest")
	proto.RegisterType((*DeleteRestaurantResponse)(nil), "DeleteRestaurantResponse")
	proto.RegisterType((*UpdateRestaurantRequest)(nil), "UpdateRestaurantRequest")
	proto.RegisterType((*UpdateRestaurantResponse)(nil), "UpdateRestaurantResponse")
	proto.RegisterType((*GetOrdersRequest)(nil), "GetOrdersRequest")
	proto.RegisterType((*GetOrdersResponse)(nil), "GetOrdersResponse")
}

func init() {
	proto.RegisterFile("src/proto/restaurants.proto", fileDescriptor_d282ef766bb01f4c)
}

var fileDescriptor_d282ef766bb01f4c = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5d, 0x8b, 0xd3, 0x50,
	0x10, 0x6d, 0xda, 0xee, 0xb6, 0x9d, 0xfd, 0x60, 0x3b, 0xec, 0xb6, 0x69, 0x8a, 0x58, 0xae, 0x2f,
	0x7d, 0xba, 0x85, 0x55, 0x10, 0x41, 0x5c, 0x3f, 0x59, 0xeb, 0xcb, 0x42, 0xc4, 0x17, 0x5f, 0x4a,
	0xec, 0x1d, 0x6b, 0xa0, 0xcd, 0x8d, 0xf7, 0xde, 0x08, 0x82, 0x3f, 0xc7, 0xdf, 0xe6, 0xef, 0x90,
	0xdc, 0xc4, 0xa4, 0x5f, 0x11, 0xeb, 0x53, 0x3b, 0x67, 0x32, 0x99, 0x33, 0x67, 0xce, 0x04, 0x86,
	0x5a, 0xcd, 0x27, 0xb1, 0x92, 0x46, 0x4e, 0x14, 0x69, 0x13, 0x24, 0x2a, 0x88, 0x8c, 0xe6, 0x16,
	0xf1, 0x86, 0x0b, 0x29, 0x17, 0x4b, 0xca, 0xf2, 0x9f, 0x92, 0xcf, 0x13, 0x5a, 0xc5, 0xe6, 0x7b,
	0x96, 0x64, 0x33, 0x00, 0xbf, 0xa8, 0xc0, 0x73, 0xa8, 0x87, 0xc2, 0x75, 0x46, 0xce, 0xb8, 0xe3,
	0xd7, 0x43, 0x81, 0x08, 0xcd, 0x28, 0x58, 0x91, 0x5b, 0xb7, 0x88, 0xfd, 0x8f, 0x97, 0x70, 0x14,
	0xae, 0x82, 0x05, 0xb9, 0x0d, 0x0b, 0x66, 0x01, 0xf6, 0xa1, 0x15, 0xea, 0x99, 0x8c, 0x29, 0x72,
	0x9b, 0x23, 0x67, 0xdc, 0xf6, 0x8f, 0x43, 0x7d, 0x17, 0x53, 0xc4, 0x9e, 0x40, 0xef, 0x96, 0x4c,
	0xd9, 0x43, 0xfb, 0xa4, 0x63, 0x19, 0x69, 0xc2, 0xfb, 0xd0, 0x14, 0x81, 0x09, 0x5c, 0x67, 0xd4,
	0x18, 0x9f, 0x5c, 0x9f, 0xf0, 0xf2, 0x19, 0xdf, 0x26, 0xd8, 0x0f, 0xb8, 0x7c, 0x21, 0xc4, 0x1a,
	0x4c, 0x5f, 0x13, 0xd2, 0xa6, 0x60, 0xe5, 0xac, 0xb1, 0x1a, 0x42, 0x27, 0x6d, 0x3e, 0xfb, 0x22,
	0x13, 0x95, 0xd3, 0x6d, 0xa7, 0xc0, 0x5b, 0x99, 0x28, 0xbc, 0x07, 0x30, 0x5f, 0x4a, 0x4d, 0x59,
	0x36, 0xe3, 0xdd, 0xb1, 0x88, 0x4d, 0x17, 0x13, 0xa5, 0xcc, 0x4f, 0xf3, 0x89, 0xd8, 0x53, 0xb8,
	0xda, 0xea, 0x9e, 0xf3, 0x7e, 0x00, 0x67, 0xa5, 0xc8, 0xb3, 0x42, 0xaf, 0xd3, 0x12, 0x9c, 0x0a,
	0xf6, 0x0c, 0xfa, 0xaf, 0x69, 0x49, 0x86, 0x76, 0xe9, 0xff, 0x53, 0xfd, 0x0d, 0xb8, 0xbb, 0xf5,
	0x87, 0x10, 0xf8, 0xe9, 0x40, 0xff, 0x43, 0x2c, 0x82, 0xff, 0x65, 0xb0, 0x77, 0xf7, 0x1b, 0x2a,
	0x37, 0xfe, 0xaa, 0x72, 0xb3, 0x52, 0xe5, 0xa3, 0x75, 0x95, 0x6f, 0xc0, 0xdd, 0x65, 0x79, 0xc8,
	0x9c, 0x8f, 0xe1, 0xe2, 0x96, 0xcc, 0x9d, 0x12, 0xa4, 0xf4, 0x41, 0x0a, 0xbf, 0x83, 0xee, 0x5a,
	0x61, 0xde, 0x72, 0x00, 0x6d, 0x99, 0x22, 0x65, 0x51, 0xcb, 0xc6, 0x53, 0x81, 0x1e, 0xb4, 0x53,
	0x9e, 0x26, 0x2c, 0x34, 0x29, 0xe2, 0xeb, 0x5f, 0x75, 0xe8, 0x96, 0x03, 0xbc, 0x27, 0xf5, 0x2d,
	0x9c, 0x13, 0xbe, 0x82, 0xf3, 0x4d, 0xeb, 0x63, 0x8f, 0x67, 0xb7, 0xc8, 0xff, 0xdc, 0x22, 0x7f,
	0x93, 0xde, 0xa2, 0xd7, 0xe7, 0xfb, 0x6f, 0x84, 0xd5, 0xf0, 0x39, 0x9c, 0x6d, 0xd8, 0x10, 0xaf,
	0xf8, 0xbe, 0xa3, 0xf0, 0x7a, 0x7c, 0xaf, 0x5b, 0x59, 0x0d, 0xa7, 0x70, 0xb1, 0x6d, 0x25, 0x74,
	0x79, 0x85, 0x3b, 0xbd, 0x01, 0xaf, 0xf2, 0x5d, 0xf6, 0xaa, 0xed, 0x6d, 0xa1, 0xcb, 0x2b, 0x6c,
	0xe6, 0x0d, 0x78, 0xd5, 0x6a, 0x59, 0x0d, 0x1f, 0x41, 0xa7, 0x90, 0x1f, 0xbb, 0x7c, 0x7b, 0x87,
	0x1e, 0xf2, 0x9d, 0xed, 0xb0, 0xda, 0xcb, 0xce, 0xc7, 0x16, 0xcf, 0x3f, 0x64, 0xc7, 0xf6, 0xe7,
	0xe1, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x93, 0xcf, 0xa2, 0xfc, 0x04, 0x00, 0x00,
}
