// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/proto/order.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f6123108f0cd38f, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity             int64    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f6123108f0cd38f, []int{1}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type GetOrdersResponse struct {
	Order                []*Order `protobuf:"bytes,1,rep,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrdersResponse) Reset()         { *m = GetOrdersResponse{} }
func (m *GetOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrdersResponse) ProtoMessage()    {}
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f6123108f0cd38f, []int{2}
}

func (m *GetOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersResponse.Unmarshal(m, b)
}
func (m *GetOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersResponse.Marshal(b, m, deterministic)
}
func (m *GetOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersResponse.Merge(m, src)
}
func (m *GetOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrdersResponse.Size(m)
}
func (m *GetOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersResponse proto.InternalMessageInfo

func (m *GetOrdersResponse) GetOrder() []*Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type AddOrderRequest struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AddOrderRequest) Reset()         { *m = AddOrderRequest{} }
func (m *AddOrderRequest) String() string { return proto.CompactTextString(m) }
func (*AddOrderRequest) ProtoMessage()    {}
func (*AddOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f6123108f0cd38f, []int{3}
}

func (m *AddOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddOrderRequest.Unmarshal(m, b)
}
func (m *AddOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddOrderRequest.Marshal(b, m, deterministic)
}
func (m *AddOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddOrderRequest.Merge(m, src)
}
func (m *AddOrderRequest) XXX_Size() int {
	return xxx_messageInfo_AddOrderRequest.Size(m)
}
func (m *AddOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddOrderRequest proto.InternalMessageInfo

func (m *AddOrderRequest) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type AddOrderResponse struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddOrderResponse) Reset()         { *m = AddOrderResponse{} }
func (m *AddOrderResponse) String() string { return proto.CompactTextString(m) }
func (*AddOrderResponse) ProtoMessage()    {}
func (*AddOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f6123108f0cd38f, []int{4}
}

func (m *AddOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddOrderResponse.Unmarshal(m, b)
}
func (m *AddOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddOrderResponse.Marshal(b, m, deterministic)
}
func (m *AddOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddOrderResponse.Merge(m, src)
}
func (m *AddOrderResponse) XXX_Size() int {
	return xxx_messageInfo_AddOrderResponse.Size(m)
}
func (m *AddOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddOrderResponse proto.InternalMessageInfo

func (m *AddOrderResponse) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type GetOrdersFromRestaurantRequest struct {
	RestaurantId         int64    `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrdersFromRestaurantRequest) Reset()         { *m = GetOrdersFromRestaurantRequest{} }
func (m *GetOrdersFromRestaurantRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrdersFromRestaurantRequest) ProtoMessage()    {}
func (*GetOrdersFromRestaurantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f6123108f0cd38f, []int{5}
}

func (m *GetOrdersFromRestaurantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersFromRestaurantRequest.Unmarshal(m, b)
}
func (m *GetOrdersFromRestaurantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersFromRestaurantRequest.Marshal(b, m, deterministic)
}
func (m *GetOrdersFromRestaurantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersFromRestaurantRequest.Merge(m, src)
}
func (m *GetOrdersFromRestaurantRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrdersFromRestaurantRequest.Size(m)
}
func (m *GetOrdersFromRestaurantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersFromRestaurantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersFromRestaurantRequest proto.InternalMessageInfo

func (m *GetOrdersFromRestaurantRequest) GetRestaurantId() int64 {
	if m != nil {
		return m.RestaurantId
	}
	return 0
}

func (m *GetOrdersFromRestaurantRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetOrdersFromRestaurantResponse struct {
	Order                []*Order `protobuf:"bytes,1,rep,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrdersFromRestaurantResponse) Reset()         { *m = GetOrdersFromRestaurantResponse{} }
func (m *GetOrdersFromRestaurantResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrdersFromRestaurantResponse) ProtoMessage()    {}
func (*GetOrdersFromRestaurantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f6123108f0cd38f, []int{6}
}

func (m *GetOrdersFromRestaurantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersFromRestaurantResponse.Unmarshal(m, b)
}
func (m *GetOrdersFromRestaurantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersFromRestaurantResponse.Marshal(b, m, deterministic)
}
func (m *GetOrdersFromRestaurantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersFromRestaurantResponse.Merge(m, src)
}
func (m *GetOrdersFromRestaurantResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrdersFromRestaurantResponse.Size(m)
}
func (m *GetOrdersFromRestaurantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersFromRestaurantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersFromRestaurantResponse proto.InternalMessageInfo

func (m *GetOrdersFromRestaurantResponse) GetOrder() []*Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func init() {
	proto.RegisterType((*Order)(nil), "Order")
	proto.RegisterType((*Product)(nil), "Product")
	proto.RegisterType((*GetOrdersResponse)(nil), "GetOrdersResponse")
	proto.RegisterType((*AddOrderRequest)(nil), "AddOrderRequest")
	proto.RegisterType((*AddOrderResponse)(nil), "AddOrderResponse")
	proto.RegisterType((*GetOrdersFromRestaurantRequest)(nil), "GetOrdersFromRestaurantRequest")
	proto.RegisterType((*GetOrdersFromRestaurantResponse)(nil), "GetOrdersFromRestaurantResponse")
}

func init() {
	proto.RegisterFile("src/proto/order.proto", fileDescriptor_6f6123108f0cd38f)
}

var fileDescriptor_6f6123108f0cd38f = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x51, 0x4f, 0xf2, 0x30,
	0x14, 0x65, 0x10, 0x60, 0xbb, 0xdf, 0x87, 0x42, 0x13, 0x01, 0xa7, 0x91, 0xa5, 0xfa, 0xc0, 0x8b,
	0x25, 0x60, 0x8c, 0xf1, 0xc9, 0x68, 0xa2, 0x86, 0x27, 0x4d, 0x7d, 0x33, 0x51, 0x33, 0x69, 0x25,
	0x4b, 0x84, 0x8e, 0xb6, 0x33, 0xe1, 0xc7, 0xfa, 0x5f, 0x0c, 0xdd, 0x56, 0x92, 0x19, 0xd4, 0xa7,
	0xed, 0x9e, 0xb3, 0x7b, 0xee, 0xb9, 0xe7, 0x0e, 0x76, 0x94, 0x9c, 0x0c, 0x62, 0x29, 0xb4, 0x18,
	0x08, 0xc9, 0xb8, 0x24, 0xe6, 0xdd, 0xdf, 0x9b, 0x0a, 0x31, 0x7d, 0xe7, 0x29, 0xf3, 0x9a, 0xbc,
	0x0d, 0xf8, 0x2c, 0xd6, 0xcb, 0x94, 0xc4, 0x1d, 0xa8, 0xde, 0xad, 0xbe, 0x45, 0x5b, 0x50, 0x8e,
	0x58, 0xd7, 0x09, 0x9c, 0xbe, 0x47, 0xcb, 0x11, 0xc3, 0xa7, 0x50, 0xbf, 0x97, 0x82, 0x25, 0x13,
	0x5d, 0xa4, 0x90, 0x0f, 0xee, 0x22, 0x09, 0xe7, 0x3a, 0xd2, 0xcb, 0x6e, 0x39, 0x70, 0xfa, 0x15,
	0x6a, 0x6b, 0x3c, 0x84, 0xd6, 0x2d, 0xd7, 0x46, 0x52, 0x51, 0xae, 0x62, 0x31, 0x57, 0x1c, 0xed,
	0x43, 0xd5, 0x18, 0xea, 0x3a, 0x41, 0xa5, 0xff, 0x6f, 0x54, 0x23, 0x86, 0xa7, 0x29, 0x88, 0xcf,
	0x60, 0xfb, 0x92, 0xb1, 0x14, 0xe2, 0x8b, 0x84, 0x2b, 0x8d, 0x8e, 0xc0, 0x8d, 0xd3, 0xe1, 0x2a,
	0xeb, 0x71, 0x49, 0xe6, 0x86, 0x5a, 0x06, 0x1f, 0x43, 0x73, 0xdd, 0x98, 0x8d, 0xda, 0x05, 0xd7,
	0xa8, 0xbe, 0x58, 0xc7, 0x75, 0x53, 0x8f, 0x19, 0x7e, 0x82, 0x03, 0x6b, 0xed, 0x46, 0x8a, 0x19,
	0xe5, 0x4a, 0x87, 0x89, 0x0c, 0xe7, 0x3a, 0x1f, 0x7b, 0x08, 0x0d, 0x69, 0xc1, 0x5c, 0xa1, 0x42,
	0xff, 0xaf, 0xc1, 0x31, 0x43, 0x6d, 0xa8, 0x29, 0x1d, 0xea, 0x44, 0x99, 0xdd, 0x3d, 0x9a, 0x55,
	0xf8, 0x02, 0x7a, 0x1b, 0xe5, 0xff, 0x92, 0xc3, 0xe8, 0xd3, 0x81, 0x86, 0x01, 0x1e, 0xb8, 0xfc,
	0x88, 0x26, 0x5c, 0xa1, 0x73, 0xf0, 0xac, 0x24, 0x6a, 0x93, 0xf4, 0x8e, 0x24, 0xbf, 0x23, 0xb9,
	0x5e, 0xdd, 0xd1, 0x47, 0xe4, 0x5b, 0xe0, 0xb8, 0x84, 0x86, 0xe0, 0xe6, 0xd9, 0xa0, 0x26, 0x29,
	0xe4, 0xeb, 0xb7, 0x48, 0x31, 0x38, 0x5c, 0x42, 0xcf, 0xd0, 0xd9, 0xb0, 0x00, 0xea, 0x91, 0x9f,
	0x93, 0xf3, 0x03, 0xf2, 0xcb, 0xee, 0xb8, 0x74, 0xe5, 0x3d, 0xd6, 0x49, 0xf6, 0x13, 0xd6, 0xcc,
	0xe3, 0xe4, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x00, 0xfb, 0x93, 0xb2, 0x02, 0x00, 0x00,
}
