// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/proto/products.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateProductRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image                []byte   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	RestaurantId         string   `protobuf:"bytes,3,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductRequest) Reset()         { *m = CreateProductRequest{} }
func (m *CreateProductRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductRequest) ProtoMessage()    {}
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37c95ea9be6a84af, []int{0}
}

func (m *CreateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductRequest.Unmarshal(m, b)
}
func (m *CreateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductRequest.Marshal(b, m, deterministic)
}
func (m *CreateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductRequest.Merge(m, src)
}
func (m *CreateProductRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductRequest.Size(m)
}
func (m *CreateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductRequest proto.InternalMessageInfo

func (m *CreateProductRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateProductRequest) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *CreateProductRequest) GetRestaurantId() string {
	if m != nil {
		return m.RestaurantId
	}
	return ""
}

type CreateProductResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductResponse) Reset()         { *m = CreateProductResponse{} }
func (m *CreateProductResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProductResponse) ProtoMessage()    {}
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37c95ea9be6a84af, []int{1}
}

func (m *CreateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductResponse.Unmarshal(m, b)
}
func (m *CreateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductResponse.Marshal(b, m, deterministic)
}
func (m *CreateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductResponse.Merge(m, src)
}
func (m *CreateProductResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProductResponse.Size(m)
}
func (m *CreateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductResponse proto.InternalMessageInfo

func (m *CreateProductResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetProductsRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductsRequest) Reset()         { *m = GetProductsRequest{} }
func (m *GetProductsRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductsRequest) ProtoMessage()    {}
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37c95ea9be6a84af, []int{2}
}

func (m *GetProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsRequest.Unmarshal(m, b)
}
func (m *GetProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsRequest.Marshal(b, m, deterministic)
}
func (m *GetProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsRequest.Merge(m, src)
}
func (m *GetProductsRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductsRequest.Size(m)
}
func (m *GetProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsRequest proto.InternalMessageInfo

func (m *GetProductsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetProductsResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image                string   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	RestaurantId         string   `protobuf:"bytes,4,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductsResponse) Reset()         { *m = GetProductsResponse{} }
func (m *GetProductsResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductsResponse) ProtoMessage()    {}
func (*GetProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37c95ea9be6a84af, []int{3}
}

func (m *GetProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsResponse.Unmarshal(m, b)
}
func (m *GetProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsResponse.Marshal(b, m, deterministic)
}
func (m *GetProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsResponse.Merge(m, src)
}
func (m *GetProductsResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductsResponse.Size(m)
}
func (m *GetProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsResponse proto.InternalMessageInfo

func (m *GetProductsResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetProductsResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetProductsResponse) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *GetProductsResponse) GetRestaurantId() string {
	if m != nil {
		return m.RestaurantId
	}
	return ""
}

type UpdateProductRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image                []byte   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	RestaurantId         string   `protobuf:"bytes,4,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductRequest) Reset()         { *m = UpdateProductRequest{} }
func (m *UpdateProductRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProductRequest) ProtoMessage()    {}
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37c95ea9be6a84af, []int{4}
}

func (m *UpdateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductRequest.Unmarshal(m, b)
}
func (m *UpdateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductRequest.Merge(m, src)
}
func (m *UpdateProductRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProductRequest.Size(m)
}
func (m *UpdateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductRequest proto.InternalMessageInfo

func (m *UpdateProductRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateProductRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateProductRequest) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *UpdateProductRequest) GetRestaurantId() string {
	if m != nil {
		return m.RestaurantId
	}
	return ""
}

type UpdateProductResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductResponse) Reset()         { *m = UpdateProductResponse{} }
func (m *UpdateProductResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProductResponse) ProtoMessage()    {}
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37c95ea9be6a84af, []int{5}
}

func (m *UpdateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductResponse.Unmarshal(m, b)
}
func (m *UpdateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductResponse.Merge(m, src)
}
func (m *UpdateProductResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProductResponse.Size(m)
}
func (m *UpdateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductResponse proto.InternalMessageInfo

func (m *UpdateProductResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteProductRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductRequest) Reset()         { *m = DeleteProductRequest{} }
func (m *DeleteProductRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProductRequest) ProtoMessage()    {}
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37c95ea9be6a84af, []int{6}
}

func (m *DeleteProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductRequest.Unmarshal(m, b)
}
func (m *DeleteProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductRequest.Marshal(b, m, deterministic)
}
func (m *DeleteProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductRequest.Merge(m, src)
}
func (m *DeleteProductRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProductRequest.Size(m)
}
func (m *DeleteProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductRequest proto.InternalMessageInfo

func (m *DeleteProductRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteProductResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductResponse) Reset()         { *m = DeleteProductResponse{} }
func (m *DeleteProductResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteProductResponse) ProtoMessage()    {}
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37c95ea9be6a84af, []int{7}
}

func (m *DeleteProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductResponse.Unmarshal(m, b)
}
func (m *DeleteProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductResponse.Marshal(b, m, deterministic)
}
func (m *DeleteProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductResponse.Merge(m, src)
}
func (m *DeleteProductResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteProductResponse.Size(m)
}
func (m *DeleteProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductResponse proto.InternalMessageInfo

func (m *DeleteProductResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateProductRequest)(nil), "CreateProductRequest")
	proto.RegisterType((*CreateProductResponse)(nil), "CreateProductResponse")
	proto.RegisterType((*GetProductsRequest)(nil), "GetProductsRequest")
	proto.RegisterType((*GetProductsResponse)(nil), "GetProductsResponse")
	proto.RegisterType((*UpdateProductRequest)(nil), "UpdateProductRequest")
	proto.RegisterType((*UpdateProductResponse)(nil), "UpdateProductResponse")
	proto.RegisterType((*DeleteProductRequest)(nil), "DeleteProductRequest")
	proto.RegisterType((*DeleteProductResponse)(nil), "DeleteProductResponse")
}

func init() {
	proto.RegisterFile("src/proto/products.proto", fileDescriptor_37c95ea9be6a84af)
}

var fileDescriptor_37c95ea9be6a84af = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x4f, 0x83, 0x40,
	0x14, 0x04, 0xac, 0x9a, 0x3e, 0x69, 0x0f, 0xaf, 0x40, 0x08, 0xa7, 0x66, 0x35, 0xb6, 0xa7, 0x35,
	0xd1, 0x9b, 0x27, 0xa3, 0x26, 0xc6, 0x9b, 0xc1, 0x78, 0xf1, 0x62, 0x90, 0x7d, 0x31, 0x24, 0x16,
	0x70, 0x77, 0xf1, 0x87, 0xf8, 0x8b, 0x0d, 0x1f, 0x7e, 0x40, 0xb7, 0x69, 0x7a, 0x01, 0xf6, 0x65,
	0x98, 0x79, 0x33, 0x03, 0x10, 0x2a, 0x99, 0x9e, 0x95, 0xb2, 0xd0, 0x45, 0x7d, 0x15, 0x55, 0xaa,
	0x15, 0x6f, 0x8e, 0x8c, 0xc0, 0xbb, 0x91, 0x94, 0x68, 0x7a, 0x68, 0xe7, 0x31, 0x7d, 0x54, 0xa4,
	0x34, 0x22, 0x8c, 0xf2, 0x64, 0x45, 0xa1, 0x3d, 0xb7, 0x97, 0xe3, 0xb8, 0x79, 0x46, 0x0f, 0xf6,
	0xb3, 0x55, 0xf2, 0x46, 0xa1, 0x33, 0xb7, 0x97, 0x6e, 0xdc, 0x1e, 0xf0, 0x18, 0x26, 0x92, 0x94,
	0x4e, 0x2a, 0x99, 0xe4, 0xfa, 0x25, 0x13, 0xe1, 0x5e, 0xf3, 0x8a, 0xfb, 0x37, 0xbc, 0x17, 0x6c,
	0x01, 0xfe, 0x40, 0x46, 0x95, 0x45, 0xae, 0x08, 0xa7, 0xe0, 0x64, 0xa2, 0x53, 0x71, 0x32, 0xc1,
	0x4e, 0x00, 0xef, 0x48, 0x77, 0x28, 0xf5, 0xb3, 0xcd, 0x10, 0xa5, 0x61, 0xd6, 0x43, 0x99, 0xc9,
	0x7e, 0x4d, 0x38, 0x26, 0x13, 0xed, 0x9a, 0x9b, 0x4c, 0x8c, 0x0c, 0x26, 0x2a, 0xf0, 0x9e, 0x4a,
	0xb1, 0x9e, 0xd5, 0xce, 0xb2, 0xee, 0x4e, 0xb2, 0x0b, 0xf0, 0x07, 0xb2, 0x1b, 0xb2, 0x3b, 0x05,
	0xef, 0x96, 0xde, 0x69, 0xdb, 0x7e, 0x35, 0xe1, 0x00, 0x67, 0x26, 0x3c, 0xff, 0x72, 0x60, 0xda,
	0x61, 0x1e, 0x49, 0x7e, 0x66, 0x29, 0xe1, 0x15, 0x4c, 0x7a, 0x45, 0xa2, 0xcf, 0x4d, 0xdf, 0x4f,
	0x14, 0x70, 0x63, 0xdf, 0xcc, 0xc2, 0x4b, 0x38, 0xfa, 0xd7, 0x1d, 0xce, 0xf8, 0x7a, 0xdf, 0x91,
	0xc7, 0x0d, 0xf5, 0x32, 0xab, 0x56, 0xef, 0x45, 0x81, 0x3e, 0x37, 0x35, 0x12, 0x05, 0xdc, 0x98,
	0x58, 0xcb, 0xd0, 0xf3, 0x8e, 0x3e, 0x37, 0x65, 0x16, 0x05, 0xdc, 0x18, 0x11, 0xb3, 0xae, 0xc7,
	0xcf, 0x87, 0xbc, 0xfd, 0x97, 0x5e, 0x0f, 0x9a, 0xdb, 0xc5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x07, 0x9d, 0x69, 0x07, 0x5f, 0x03, 0x00, 0x00,
}
