services:
  products:
    build: .
    ports:
      - "7000:7000"

  products_db:
    image: 'bitnami/mongodb:4.4'
    restart: always
    ports: 
      - "7001:27017"
    volumes:
      - product_db:/bitnami/mongodb
    environment:
      - MONGODB_ROOT_USER=${MONGODB_USER}
      - MONGODB_ROOT_PASSWORD=${MONGODB_PASS}
      - MONGODB_DATABASE=${MONGODB_DB}
  
volumes:
  product_db: